@startuml
package TestClassDiag {
	package subPackage {
		class Class1 {
			tst: PrimitiveTypes.String
		}
		class Class2 {
		}
		Class2 <|-- Class1
	}
	class Class1 {
		class2: Class3 [0..1]
		p1: PrimitiveTypes.Integer
		p2: PrimitiveTypes.Integer [*]
	}
	class Class3 {
	}
	interface SubIntf {
	}
	interface SuperInterface {
	}
	enum TestEnum {
		Literal1
		Literal2
	}
	dataclass TestDT {
		attribute1: PrimitiveTypes.Integer
	}
	class Class4 {
	}
	note top of Class4: Class1 inherits from Class4 implementing another interface. Test checks that PlantUML representation of Class1 only contains directly implemented interfaces 
	interface AnotherIntf {
	}
	Class4 <|-- Class1
	SubIntf <|.. Class1
	Class1 ..> SubIntf
	TestClassDiag.subPackage.Class2 <|-- Class3
	SuperInterface <|-- SubIntf
	AnotherIntf <|.. Class4
	Class3 "class2 0..1" <-- "class1" Class1
}
note top of TestClassDiag: Global comment\n
@enduml