@startuml
'Global comment
package TestClassDiag {
	package subPackage {
		class Class1 {
			tst: PrimitiveTypes.String
		}
		class Class2 {
		}
	}
	class Class1 {
		class2: Class3 [0..1]
		p1: PrimitiveTypes.Integer
		p2: PrimitiveTypes.Integer [*]
	}
	class Class3 {
	}
	interface SubIntf {
	}
	interface SuperInterface {
	}
	enum TestEnum {
		Literal1
		Literal2
	}
	dataclass TestDT {
		attribute1: PrimitiveTypes.Integer
	}
	'Class1 inherits from Class4 implementing another interface. Test checks that PlantUML representation of Class1 only contains directly implemented interfaces 
	class Class4 {
	}
	interface AnotherIntf {
	}
	subPackage.Class2 <|-- subPackage.Class1
	Class4 <|-- Class1
	SubIntf <|.. Class1
	subPackage.Class2 <|-- Class3
	Class3 ..> PrimitiveTypes.Integer
	SuperInterface <|-- SubIntf
	AnotherIntf <|.. Class4
	Class3 "class2 0..1" <-- "class1" Class1
}
@enduml