name: HelloWorld on PlantUML release

on:
  # Triggered by external repository_dispatch event (from plantuml repo)
  repository_dispatch:
    types: [plantuml-release]
  # Temporary: allows manual trigger via GitHub UI for testing purposes
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "HelloWorld - triggered by PlantUML release!"
      - name: Print Release Details
        run: echo "PlantUML ${{ github.event.client_payload.release }}, snapshot? ${{ github.event.client_payload.snapshot }}"
