name: PlantUML library release for Eclipse

on:
  push:
    branches:
      - automate-releases
  # Triggered by external repository_dispatch event (from plantuml repo)
  #repository_dispatch:
  #  types: [plantuml-release]
  # Allow manual triggering via GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Add latest PlantUML lib to composite update site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TODO: for now we only prepare the git commit for publishing the update site at GitHub pages
        run: gradle clean gitCommitPlantUmlLibUpdateSiteToGhPages
