name: PlantUML library release for Eclipse

on:
  # Triggered by external repository_dispatch event (from plantuml repo)
  #repository_dispatch:
  #  types: [plantuml-release]
  # Allow manual triggering via GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Update Eclipse projects' versions
        run: echo "Updating versions not implemented yet!"
      - name: Build PlantUML lib update site
        run: mvn --batch-mode clean package -f plantuml-lib/pom.xml
      - name: Update composite update site contents
        run: echo "Updating composite update site contents not implemented yet!"
      - name: Build composite update site
        run: mvn --batch-mode clean package -f composite-repository/pom.xml
      - name: Deploy composite update site to GitHub pages
        run: echo "Deploying composite update site to GitHub pages not implemented yet!"
