name: PlantUML library release for Eclipse

on:
  push:
    branches:
      - automate-releases
  # Triggered by external repository_dispatch event (from plantuml repo)
  #repository_dispatch:
  #  types: [plantuml-release]
  # Allow manual triggering via GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Clone GitHub pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: build/gh-pages

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build latest PlantUML lib update site
        run: |
          echo "Files after check-out:"
          ls -al build/gh-pages
          ./gradlew updateGhPagesFiles --no-daemon
          echo "Files after adapting files for GH pages:"
          ls -al build/gh-pages
          ./gradlew addLatestPlantUmlUpdateSiteToGhPages --no-daemon
          echo "Files after building update site:"
          ls -al build/gh-pages
          echo "Files in Maven build folder:"
          ls -al plantuml-lib/net.sourceforge.plantuml.library.repository/target/repository

      - name: Save artifacts for the git push
        uses: actions/upload-artifact@v4
        with:
          name: 'gh-pages-update'
          path: build/gh-pages/
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone GitHub pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Load artifacts for the git push
        uses: actions/download-artifact@v4
        with:
          name: 'gh-pages-update'

      - name: Push update site to GitHub pages
        # see https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
        run: |
          echo $GITHUB_WORKSPACE
          ls -al
          git status
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Add new PlantUML lib update site version"
#          git push
