name: PlantUML library release for Eclipse

on:
  push:
    branches:
      - automate-releases
  # Triggered by external repository_dispatch event (from plantuml repo)
  #repository_dispatch:
  #  types: [plantuml-release]
  # Allow manual triggering via GitHub UI
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Clone GitHub pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: build/gh-pages
      - name: Build latest PlantUML lib update site
        run: gradle updateGhPagesFiles addLatestPlantUmlUpdateSiteToGhPages
      - name: Push update site to GitHub pages
        # see https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
        run: |
          cd build/gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git status
          git add --all
          git commit -m "Add new PlantUML lib update site version"
#          git push
